[package]
name = "mlp"
authors = ["Lydia Shin <lydiazs2@illinois.edu>", "William Du <wwdu2@illinois.edu>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]